project:
  type: website
  output-dir: docs
website:
  title: "Biocontrole de Ferrugem Asiática da Soja"
  favicon: images/PhapaK8108b.png
  navbar:
    background: "#323f45"
    left:
      - href: index.qmd
        text: Home
      - text: "Exploração inicial de dados"
        menu:
          - text: "Tabela"
            file: table.qmd
          - text: "Gráficos"
            file: exp_dad.qmd
      - text: "Análise de dados"
        menu:
          - text: "Área Abaixo da Curva de Progresso da Doença"
            file: aaacpd.qmd
          - text: "Transformação"
            file: transformacao.qmd
          - text: "Modelo misto"
            file: modelo_misto.qmd
          - text: "Ranqueamento da AACPD"
            file: ranqueamento.qmd
      - text: "Sobre os autores"
        file: sobre.qmd
        
    page-navigation: true
    page-footer: 
      left: "Copyright 2023, D.O. Ramos & P.T.S. Nogueira"
      background: "#323f45"
format:
  html:
    theme:
      light: sandstone
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    warning: false

editor: visual

