project:
  type: website

website:
  title: "Biocontrole de Ferrugem Asiática da Soja"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Exploração inicial de dados"
        menu:
          - text: "Tabela"
            file: table.qmd
          - text: "Gráficos"
            file: exp_dad.qmd
      - text: "Análise de dados"
        menu:
          - text: "Área Abaixo da Curva de Progresso da Doença"
            file: aaacpd.qmd
          - text: "Transformação"
            file: transformacao.qmd
          - text: "Modelo misto"
            file: modelo_misto.qmd
          - text: "Ranqueamento da AACPD"
            file: ranqueamento.qmd
      - text: "Sobre os autores"
        file: sobre.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

